server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
spring:
  security:
    s2s-token: ${API_KEY}

    oauth2:
      resourceserver:
        jwt: {}


jwt:
  issuer: legendme-login-svc
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.boot: WARN
    org.springframework.web: WARN
    org.springframework.security: INFO
    org.apache.catalina: WARN
    org.apache.coyote: WARN
    org.hibernate: WARN